### ISSUE TITLE
Compilation error in file lib/axon_onnx/shared.ex 

### ISSUE THREAD

**Issue by TheEndIsNear** [elixir-nx/axon_onnx#55]
I am getting the following error when attempting to install axon_onnx in livebook. 

== Compilation error in file lib/axon_onnx/shared.ex ==
** (CompileError) lib/axon_onnx/shared.ex:58: undefined function transform/2 (there is no such import)
    (nx 0.7.1) lib/nx/defn/compiler.ex:832: Nx.Defn.Compiler.compile_error!/3
    (nx 0.7.1) lib/nx/defn/compiler.ex:429: Nx.Defn.Compiler.normalize/2
    (elixir 1.16.2) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.2) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.7.1) lib/nx/defn/compiler.ex:422: Nx.Defn.Compiler.normalize/2
    (elixir 1.16.2) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.2) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (nx 0.7.1) lib/nx/defn/compiler.ex:422: Nx.Defn.Compiler.normalize/2

The command that I am running in the setup.

Mix.install([
{:axon_onnx, "~> 0.4"},
{:axon, "~> 0.5"},
{:nx, "~> 0.5"},
{:exla, "~> 0.5"},
{:stb_image, "~> 0.6"},
{:kino, "~> 0.8"},
])

I am running elixir 1.16.2 with OTP/26 with Livebook 0.12.1 on Ubuntu 20.04 in Windows Subsystem for Linux.

**Comment by josevalim** [comment]
You can use main for now.

**Comment by TheEndIsNear** [comment]
That fixed it thanks Jose!

**Comment by khari998** [comment]
Getting the same error

**Comment by Eiji7** [comment]
2 months without any update? Today someone asked about this issue on [#Elixir Chat](https://elixirforum.com/chat/c/elixir-chat/2) too.

**Comment by khari998** [comment]
> 2 months without any update? Today someone asked about this issue on [#Elixir Chat](https://elixirforum.com/chat/c/elixir-chat/2) too.

I switched to using Ortex instead. Even on the latest main branch from the repo I was having other issues.

**Comment by sergchernata** [comment]
Here's a workaround:

```
{:axon_onnx, github: "elixir-nx/axon_onnx"}
```

https://elixirforum.com/t/error-using-axononnx-v0-4-0-undefined-function-transform-2/63326/2?u=sergchernata
